version: "2"
services:
  php:
    build: .
    tmpfs:
      - /tmp:mode=1777
    links:
      - mysql
    environment:
      - MAGENTO_VERSION=2.3
      - TEST_SUITE=integration
    command: .ci-scripts/run.sh

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_HOST: mysql
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "magento2"
      MYSQL_SQL_TO_RUN: 'GRANT ALL ON *.* TO "root"@"%";'
    tmpfs:
      - /tmp:mode=1777
      - /var/lib/mysql:mode=1777
    ports:
      - 3306
