name: ExtDN M2 PHPStan
on: [push, pull_request]

jobs:
  phpstan:
    name: M2 PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-phpstan@master
        with:
          composer_name: ${{ secrets.COMPOSER_NAME }}
    env:
      MAGENTO_PRE_INSTALL_SCRIPT: .github/workflows/extdn-integration-tests-pre-install.sh
