name: ExtDN Actions
on: [push, pull_request]

jobs:
  unit-tests:
    name: Magento 2 Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: M2 Unit Tests with Magento 2.3.5
        uses: extdn/github-actions-m2/magento-unit-tests@master
        env:
            MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }}
            MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}
        with:
            module_name: Yireo_Webp2
            composer_name: yireo/magento2-webp2
            ce_version: 2.3.5


